apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mini-drop
resources:
  - namespace.yaml
  - configmap.yaml
  - migrate-job.yaml
  - control-plane.yaml
  - diagnosis-worker.yaml
  - analyzer.yaml
  - apiserver.yaml
  - web.yaml
  - native-agent.yaml
  - disruption-budgets.yaml
  - autoscaling.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: mini-drop
