const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]));
let agents=[],tasks=[],selectedTask=null;
const statusText={NEW:'新建',PENDING:'等待执行',RUNNING:'正在采集',UPLOADING:'正在分析',DONE:'已完成',FAILED:'失败'};
const reasonText={'task accepted':'任务已创建，等待 Agent 领取','claimed by agent':'Agent 已领取任务','collector finished; uploading':'采集完成，正在上传分析','analyzer produced visualizations':'分析器已生成可视化结果','agent connected or recovered':'Agent 已连接或恢复','no heartbeat for 30s':'超过 30 秒未收到心跳'};
const collectorText={perf:'CPU / perf',ebpf:'eBPF 内核探针',pyspy:'Python 调用栈'};
const auditText={AGENT_ONLINE:'Agent 上线或恢复',AGENT_OFFLINE:'Agent 离线'};
const zhStatus=s=>statusText[s]||s,zhReason=s=>reasonText[s]||s,zhCollector=s=>collectorText[s]||s;
async function api(path,opts){let r=await fetch('/api'+path,{headers:{'content-type':'application/json'},...opts}),d=await r.json();if(!r.ok)throw Error(d.error||r.status);return d}
function showToast(text){let t=$('#toast');t.textContent=text;t.classList.remove('hidden');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.add('hidden'),2800)}
function showPage(id,button){['overview','agents','audit'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===button))}
function openModal(){if(!agents.some(x=>x.online))return showToast('当前没有在线 Agent，暂时无法创建任务');$('#formError').classList.add('hidden');$('#modal').showModal()}
async function createTask(e){e.preventDefault();let error=$('#formError'),body={agent_id:$('#agent').value,pid:+$('#pid').value,duration:+$('#duration').value,rate:+$('#rate').value,collector:$('#collector').value,continuous:$('#continuous').checked};error.classList.add('hidden');try{let task=await api('/tasks',{method:'POST',body:JSON.stringify(body)});$('#modal').close();showToast(`任务 ${task.id} 已下发`);await refresh()}catch(err){error.textContent=`任务创建失败：${err.message}`;error.classList.remove('hidden')}}
function when(ts){return new Date(ts*1000).toLocaleTimeString('zh-CN',{hour12:false})}
function renderFlame(node){let leaves=[];function walk(n,d){if(!n.children?.length)leaves.push({name:n.name,value:n.value,depth:d});else n.children.forEach(x=>walk(x,d+1))}walk(node,0);let max=Math.max(...leaves.map(x=>x.value),1);return leaves.map(x=>`<div title="${esc(x.name)}：${x.value}" style="height:${40+x.value/max*160}px">${esc(x.name)}<br><b>${x.value}</b></div>`).join('')}
async function detail(id){selectedTask=id;let t=await api('/tasks/'+id),r=t.result;document.querySelectorAll('#tasks tr').forEach(x=>x.classList.toggle('selected',x.dataset.id===id));let degraded=r?.collector_meta?.degraded?`<span>降级原因：${esc(r.collector_meta.reason||r.collector_meta.stderr)}</span>`:'';$('#detail').classList.remove('hidden');$('#detail').innerHTML=`<div class="detail-header"><div><h2>任务 ${esc(id)}</h2><div class="detail-meta"><span>采集器：${zhCollector(t.collector)}</span><span>目标 PID：${t.pid}</span>${r?`<span>后端：${esc(r.collector_meta.backend)}</span><span>结果指纹：${r.fingerprint}</span>${degraded}`:''}</div></div><span class="pill ${t.status}">${zhStatus(t.status)}</span></div>${r?`<div class="detail-grid"><div class="analysis-block"><h3>采样火焰图</h3><div class="flame">${renderFlame(r.flamegraph)}</div>${r.histogram?.length?`<h3 style="margin-top:24px">内核写入分布</h3><div class="histogram">${r.histogram.slice().sort((a,b)=>b.count-a.count).slice(0,16).map(x=>`<div><span>${esc(x.bucket)}</span><b style="width:${Math.min(100,12+x.count/8)}%">${x.count}</b></div>`).join('')}</div>`:''}</div><aside class="analysis-block"><h3>热点函数 TopN</h3>${r.top.map(x=>`<div class="top-row"><span>${esc(x.name)}</span><b>${x.samples}</b></div>`).join('')}<h3 style="margin-top:24px">性能归因</h3>${r.attribution.map(x=>`<div class="attribution"><b>${esc(x.conclusion)}</b><code>证据 ${esc(JSON.stringify(x.evidence))}</code><code>规则 ${esc(x.rule)}</code></div>`).join('')}</aside></div>`:`<div class="empty"><b>正在等待分析结果</b><p>Agent 完成采集后，这里会显示火焰图与性能归因。</p></div>`}<div class="history"><h3>状态历史</h3>${t.transitions.map(x=>`<div class="audit-row"><b>${zhStatus(x.from_status||'NEW')} → ${zhStatus(x.to_status)}</b><span>${esc(zhReason(x.reason))} · ${when(x.created_at)}</span></div>`).join('')}</div>`;$('#detail').scrollIntoView({behavior:'smooth',block:'start'})}
async function refresh(){try{let audit;[agents,tasks,audit]=await Promise.all([api('/agents'),api('/tasks'),api('/audit')]);$('#mAgents').textContent=agents.filter(x=>x.online).length;$('#mRunning').textContent=tasks.filter(x=>['RUNNING','UPLOADING'].includes(x.status)).length;$('#mDone').textContent=tasks.filter(x=>x.status==='DONE').length;$('#mFailed').textContent=tasks.filter(x=>x.status==='FAILED').length;$('#taskEmpty').classList.toggle('hidden',tasks.length>0);$('#tasks').innerHTML=tasks.map(t=>`<tr data-id="${t.id}" class="${selectedTask===t.id?'selected':''}" onclick="detail('${t.id}')"><td>${t.id}</td><td>${zhCollector(t.collector)}</td><td>${t.pid}</td><td><span class="pill ${t.status}">${zhStatus(t.status)}</span></td><td>${esc(zhReason(t.reason))}</td><td>${when(t.created_at)}</td></tr>`).join('');$('#agent').innerHTML=agents.filter(x=>x.online).map(x=>`<option>${esc(x.id)}</option>`).join('');$('#agentCards').innerHTML=agents.map(x=>`<article class="agent-row"><div><strong>${esc(x.id)}</strong><small>${esc(x.hostname)}</small></div><span>${esc(x.version)}</span><span>最后心跳 ${when(x.last_seen)}</span><span class="pill ${x.online?'DONE':'FAILED'}">${x.online?'在线':'离线'}</span></article>`).join('');$('#auditRows').innerHTML=audit.length?audit.map(x=>`<div class="audit-row"><b>${esc(auditText[x.kind]||x.kind)} · ${esc(x.subject)}</b><span>${esc(zhReason(x.message))} · ${when(x.created_at)}</span></div>`).join(''):`<div class="empty"><b>暂无审计记录</b><p>Agent 上线、离线与恢复事件会显示在这里。</p></div>`}catch(e){showToast(`数据刷新失败：${e.message}`)}}
refresh();setInterval(refresh,2000);
