const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]));
let agents=[],tasks=[];
const statusText={PENDING:'等待执行',RUNNING:'正在采集',UPLOADING:'正在分析',DONE:'已完成',FAILED:'失败'};
const reasonText={'task accepted':'任务已创建，等待 Agent 领取','claimed by agent':'Agent 已领取任务','collector finished; uploading':'采集完成，正在上传分析','analyzer produced visualizations':'分析器已生成可视化结果'};
const collectorText={perf:'CPU / perf',ebpf:'eBPF 内核探针',pyspy:'Python 调用栈'};
const auditText={AGENT_ONLINE:'Agent 上线/恢复',AGENT_OFFLINE:'Agent 离线'};
const zhStatus=s=>statusText[s]||s, zhReason=s=>reasonText[s]||s, zhCollector=s=>collectorText[s]||s;
async function api(path,opts){let r=await fetch('/api'+path,{headers:{'content-type':'application/json'},...opts});let d=await r.json();if(!r.ok)throw Error(d.error||r.status);return d}
function showPage(id){['overview','agents','audit'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}
function openModal(){if(!agents.length)return alert('当前没有在线 Agent');$('#modal').showModal()}
async function createTask(e){e.preventDefault();let body={agent_id:$('#agent').value,pid:+$('#pid').value,duration:+$('#duration').value,rate:+$('#rate').value,collector:$('#collector').value,continuous:$('#continuous').checked};await api('/tasks',{method:'POST',body:JSON.stringify(body)});$('#modal').close();refresh()}
function when(ts){return new Date(ts*1000).toLocaleTimeString()}
function renderFlame(node){let leaves=[];function walk(n,d){if(!n.children?.length)leaves.push({name:n.name,value:n.value,depth:d});else n.children.forEach(x=>walk(x,d+1))}walk(node,0);let max=Math.max(...leaves.map(x=>x.value),1);return leaves.map(x=>`<div title="${esc(x.name)}: ${x.value}" style="height:${35+x.value/max*145}px">${esc(x.name)}<br><b>${x.value}</b></div>`).join('')}
async function detail(id){let t=await api('/tasks/'+id),r=t.result;$('#detail').classList.remove('hidden');$('#detail').innerHTML=`<div class="panel-head"><h2>任务详情 ${esc(id)}</h2><span class="pill ${t.status}">${zhStatus(t.status)}</span></div>${r?`<p class="muted">采集器：${zhCollector(t.collector)} · 结果指纹：${r.fingerprint} · 后端：${esc(r.collector_meta.backend)} ${r.collector_meta.degraded?'· 降级运行：'+esc(r.collector_meta.reason||r.collector_meta.stderr):''}</p><div class="flame">${renderFlame(r.flamegraph)}</div>${r.histogram?.length?`<h3>采集器分布</h3><div class="histogram">${r.histogram.slice(0,20).map(x=>`<div><span>${esc(x.bucket)}</span><b style="width:${Math.min(100,10+x.count/8)}%">${x.count}</b></div>`).join('')}</div>`:''}<div class="charts"><div><h3>热点函数 TopN</h3>${r.top.map(x=>`<div class="top-row"><span>${esc(x.name)}</span><b>${x.samples}</b></div>`).join('')}</div><div><h3>可验证性能归因</h3>${r.attribution.map(x=>`<pre>${esc(x.conclusion)}\n证据：${esc(JSON.stringify(x.evidence))}\n匹配规则：${esc(x.rule)}</pre>`).join('')}</div></div>`:`<p>正在等待分析器生成结果。</p>`}<h3>任务状态历史</h3>${t.transitions.map(x=>`<div class="audit-row"><b>${zhStatus(x.from_status||'NEW')} → ${zhStatus(x.to_status)}</b> · ${esc(zhReason(x.reason))} · ${when(x.created_at)}</div>`).join('')}`;$('#detail').scrollIntoView({behavior:'smooth'})}
async function refresh(){try{[agents,tasks,audit]=await Promise.all([api('/agents'),api('/tasks'),api('/audit')]);$('#mAgents').textContent=agents.filter(x=>x.online).length;$('#mRunning').textContent=tasks.filter(x=>['RUNNING','UPLOADING'].includes(x.status)).length;$('#mDone').textContent=tasks.filter(x=>x.status==='DONE').length;$('#mFailed').textContent=tasks.filter(x=>x.status==='FAILED').length;$('#tasks').innerHTML=tasks.map(t=>`<tr onclick="detail('${t.id}')"><td><b>${t.id}</b></td><td>${zhCollector(t.collector)}</td><td>${t.pid}</td><td><span class="pill ${t.status}">${zhStatus(t.status)}</span></td><td>${esc(zhReason(t.reason))}</td><td>${when(t.created_at)}</td></tr>`).join('');$('#agent').innerHTML=agents.filter(x=>x.online).map(x=>`<option>${esc(x.id)}</option>`).join('');$('#agentCards').innerHTML=agents.map(x=>`<div class="card"><b>${esc(x.id)}</b><p>${esc(x.hostname)}</p><span class="pill ${x.online?'DONE':'FAILED'}">${x.online?'在线':'离线'}</span><p class="muted">最后心跳：${when(x.last_seen)}</p></div>`).join('');$('#auditRows').innerHTML=audit.map(x=>`<div class="audit-row"><b>${esc(auditText[x.kind]||x.kind)}</b> · ${esc(x.subject)}<br><span class="muted">${esc(x.message)} · ${when(x.created_at)}</span></div>`).join('')}catch(e){console.error(e)}}
refresh();setInterval(refresh,2000);
