const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]));
let agents=[],tasks=[];
async function api(path,opts){let r=await fetch('/api'+path,{headers:{'content-type':'application/json'},...opts});let d=await r.json();if(!r.ok)throw Error(d.error||r.status);return d}
function showPage(id){['overview','agents','audit'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}
function openModal(){if(!agents.length)return alert('No online agent yet');$('#modal').showModal()}
async function createTask(e){e.preventDefault();let body={agent_id:$('#agent').value,pid:+$('#pid').value,duration:+$('#duration').value,rate:+$('#rate').value,collector:$('#collector').value,continuous:$('#continuous').checked};await api('/tasks',{method:'POST',body:JSON.stringify(body)});$('#modal').close();refresh()}
function when(ts){return new Date(ts*1000).toLocaleTimeString()}
function renderFlame(node){let leaves=[];function walk(n,d){if(!n.children?.length)leaves.push({name:n.name,value:n.value,depth:d});else n.children.forEach(x=>walk(x,d+1))}walk(node,0);let max=Math.max(...leaves.map(x=>x.value),1);return leaves.map(x=>`<div title="${esc(x.name)}: ${x.value}" style="height:${35+x.value/max*145}px">${esc(x.name)}<br><b>${x.value}</b></div>`).join('')}
async function detail(id){let t=await api('/tasks/'+id),r=t.result;$('#detail').classList.remove('hidden');$('#detail').innerHTML=`<div class="panel-head"><h2>Profile ${esc(id)}</h2><span class="pill ${t.status}">${t.status}</span></div>${r?`<p class="muted">Collector: ${esc(t.collector)} · fingerprint ${r.fingerprint} · backend ${esc(r.collector_meta.backend)} ${r.collector_meta.degraded?'· DEGRADED: '+esc(r.collector_meta.reason||r.collector_meta.stderr):''}</p><div class="flame">${renderFlame(r.flamegraph)}</div>${r.histogram?.length?`<h3>Collector distribution</h3><div class="histogram">${r.histogram.slice(0,20).map(x=>`<div><span>${esc(x.bucket)}</span><b style="width:${Math.min(100,10+x.count)}%">${x.count}</b></div>`).join('')}</div>`:''}<div class="charts"><div><h3>Top functions</h3>${r.top.map(x=>`<div class="top-row"><span>${esc(x.name)}</span><b>${x.samples}</b></div>`).join('')}</div><div><h3>Verifiable attribution</h3>${r.attribution.map(x=>`<pre>${esc(x.conclusion)}\nEvidence: ${esc(JSON.stringify(x.evidence))}\nRule: ${esc(x.rule)}</pre>`).join('')}</div></div>`:`<p>Waiting for analyzer output.</p>`}<h3>State history</h3>${t.transitions.map(x=>`<div class="audit-row"><b>${esc(x.from_status||'NEW')} → ${esc(x.to_status)}</b> · ${esc(x.reason)} · ${when(x.created_at)}</div>`).join('')}`;$('#detail').scrollIntoView({behavior:'smooth'})}
async function refresh(){try{[agents,tasks,audit]=await Promise.all([api('/agents'),api('/tasks'),api('/audit')]);$('#mAgents').textContent=agents.filter(x=>x.online).length;$('#mRunning').textContent=tasks.filter(x=>['RUNNING','UPLOADING'].includes(x.status)).length;$('#mDone').textContent=tasks.filter(x=>x.status==='DONE').length;$('#mFailed').textContent=tasks.filter(x=>x.status==='FAILED').length;$('#tasks').innerHTML=tasks.map(t=>`<tr onclick="detail('${t.id}')"><td><b>${t.id}</b></td><td>${esc(t.collector)}</td><td>${t.pid}</td><td><span class="pill ${t.status}">${t.status}</span></td><td>${esc(t.reason)}</td><td>${when(t.created_at)}</td></tr>`).join('');$('#agent').innerHTML=agents.filter(x=>x.online).map(x=>`<option>${esc(x.id)}</option>`).join('');$('#agentCards').innerHTML=agents.map(x=>`<div class="card"><b>${esc(x.id)}</b><p>${esc(x.hostname)}</p><span class="pill ${x.online?'DONE':'FAILED'}">${x.online?'ONLINE':'OFFLINE'}</span><p class="muted">Last heartbeat ${when(x.last_seen)}</p></div>`).join('');$('#auditRows').innerHTML=audit.map(x=>`<div class="audit-row"><b>${esc(x.kind)}</b> · ${esc(x.subject)}<br><span class="muted">${esc(x.message)} · ${when(x.created_at)}</span></div>`).join('')}catch(e){console.error(e)}}
refresh();setInterval(refresh,2000);
