// Code generated by scripts/generate_status_contracts.py; DO NOT EDIT.
package taskstatus

const (
	CollectionCreated = "CREATED"
	CollectionQueued = "QUEUED"
	CollectionDelivered = "DELIVERED"
	CollectionRunning = "RUNNING"
	CollectionUploading = "UPLOADING"
	CollectionCollected = "COLLECTED"
	CollectionFailed = "FAILED"
	CollectionCanceled = "CANCELED"
	AnalysisPending = "PENDING"
	AnalysisRunning = "RUNNING"
	AnalysisRetry = "RETRY"
	AnalysisSuccess = "SUCCESS"
	AnalysisFailed = "FAILED"
	AnalysisCanceled = "CANCELED"
)
