// Code generated by scripts/generate_error_code_contracts.py; DO NOT EDIT.
package errorcode

type Code string
type Metadata struct { ID int; Phase string; Retryable bool; GRPCCode string; UserMessageZH string }

const (
	None Code = "NONE"
	InvalidArgument Code = "INVALID_ARGUMENT"
	AuthenticationFailed Code = "AUTHENTICATION_FAILED"
	AuthorizationDenied Code = "AUTHORIZATION_DENIED"
	AgentNotFound Code = "AGENT_NOT_FOUND"
	AgentOffline Code = "AGENT_OFFLINE"
	AgentCapabilityMissing Code = "AGENT_CAPABILITY_MISSING"
	TaskKindUnsupported Code = "TASK_KIND_UNSUPPORTED"
	TargetNotFound Code = "TARGET_NOT_FOUND"
	TargetIdentityChanged Code = "TARGET_IDENTITY_CHANGED"
	RunnerNotFound Code = "RUNNER_NOT_FOUND"
	RunnerStartFailed Code = "RUNNER_START_FAILED"
	RunnerExitNonzero Code = "RUNNER_EXIT_NONZERO"
	RunnerTimeout Code = "RUNNER_TIMEOUT"
	TaskCanceled Code = "TASK_CANCELED"
	ResourceLimitExceeded Code = "RESOURCE_LIMIT_EXCEEDED"
	ArtifactPathInvalid Code = "ARTIFACT_PATH_INVALID"
	ArtifactHashFailed Code = "ARTIFACT_HASH_FAILED"
	UploadAuthorizationInvalid Code = "UPLOAD_AUTHORIZATION_INVALID"
	UploadFailed Code = "UPLOAD_FAILED"
	ResultAuthorityInvalid Code = "RESULT_AUTHORITY_INVALID"
	ResultMalformed Code = "RESULT_MALFORMED"
	StorageUnavailable Code = "STORAGE_UNAVAILABLE"
	DatabaseUnavailable Code = "DATABASE_UNAVAILABLE"
	AnalysisInputInvalid Code = "ANALYSIS_INPUT_INVALID"
	AnalysisTimeout Code = "ANALYSIS_TIMEOUT"
	AnalysisRetryExhausted Code = "ANALYSIS_RETRY_EXHAUSTED"
	InternalError Code = "INTERNAL_ERROR"
)

var ByCode = map[Code]Metadata{
	None: {ID: 0, Phase: "none", Retryable: false, GRPCCode: "OK", UserMessageZH: ""},
	InvalidArgument: {ID: 1000, Phase: "validation", Retryable: false, GRPCCode: "INVALID_ARGUMENT", UserMessageZH: "任务参数不合法"},
	AuthenticationFailed: {ID: 1001, Phase: "authorization", Retryable: false, GRPCCode: "UNAUTHENTICATED", UserMessageZH: "调用方身份校验失败"},
	AuthorizationDenied: {ID: 1002, Phase: "authorization", Retryable: false, GRPCCode: "PERMISSION_DENIED", UserMessageZH: "没有执行该操作的权限"},
	AgentNotFound: {ID: 1100, Phase: "dispatch", Retryable: false, GRPCCode: "NOT_FOUND", UserMessageZH: "目标 Agent 不存在"},
	AgentOffline: {ID: 1101, Phase: "dispatch", Retryable: true, GRPCCode: "UNAVAILABLE", UserMessageZH: "目标 Agent 当前离线"},
	AgentCapabilityMissing: {ID: 1102, Phase: "dispatch", Retryable: false, GRPCCode: "FAILED_PRECONDITION", UserMessageZH: "目标 Agent 不具备所需采集能力"},
	TaskKindUnsupported: {ID: 1103, Phase: "dispatch", Retryable: false, GRPCCode: "INVALID_ARGUMENT", UserMessageZH: "不支持的采集类型"},
	TargetNotFound: {ID: 1200, Phase: "collection", Retryable: false, GRPCCode: "NOT_FOUND", UserMessageZH: "目标进程不存在"},
	TargetIdentityChanged: {ID: 1201, Phase: "collection", Retryable: false, GRPCCode: "FAILED_PRECONDITION", UserMessageZH: "目标 PID 已被复用或进程身份发生变化"},
	RunnerNotFound: {ID: 1202, Phase: "collection", Retryable: false, GRPCCode: "FAILED_PRECONDITION", UserMessageZH: "采集工具不可用"},
	RunnerStartFailed: {ID: 1203, Phase: "collection", Retryable: false, GRPCCode: "FAILED_PRECONDITION", UserMessageZH: "采集进程启动失败"},
	RunnerExitNonzero: {ID: 1204, Phase: "collection", Retryable: false, GRPCCode: "INTERNAL", UserMessageZH: "采集工具异常退出"},
	RunnerTimeout: {ID: 1205, Phase: "collection", Retryable: true, GRPCCode: "DEADLINE_EXCEEDED", UserMessageZH: "采集任务超时"},
	TaskCanceled: {ID: 1206, Phase: "collection", Retryable: false, GRPCCode: "CANCELLED", UserMessageZH: "任务已取消"},
	ResourceLimitExceeded: {ID: 1207, Phase: "collection", Retryable: true, GRPCCode: "RESOURCE_EXHAUSTED", UserMessageZH: "采集资源预算不足"},
	ArtifactPathInvalid: {ID: 1300, Phase: "upload", Retryable: false, GRPCCode: "PERMISSION_DENIED", UserMessageZH: "采集文件路径不安全"},
	ArtifactHashFailed: {ID: 1301, Phase: "upload", Retryable: false, GRPCCode: "DATA_LOSS", UserMessageZH: "采集文件完整性计算失败"},
	UploadAuthorizationInvalid: {ID: 1302, Phase: "upload", Retryable: true, GRPCCode: "FAILED_PRECONDITION", UserMessageZH: "短时上传授权缺失或已过期"},
	UploadFailed: {ID: 1303, Phase: "upload", Retryable: true, GRPCCode: "UNAVAILABLE", UserMessageZH: "采集文件上传失败"},
	ResultAuthorityInvalid: {ID: 1400, Phase: "report", Retryable: false, GRPCCode: "PERMISSION_DENIED", UserMessageZH: "结果不属于当前任务尝试"},
	ResultMalformed: {ID: 1401, Phase: "report", Retryable: false, GRPCCode: "INVALID_ARGUMENT", UserMessageZH: "结果元数据格式不合法"},
	StorageUnavailable: {ID: 1500, Phase: "infrastructure", Retryable: true, GRPCCode: "UNAVAILABLE", UserMessageZH: "对象存储暂不可用"},
	DatabaseUnavailable: {ID: 1501, Phase: "infrastructure", Retryable: true, GRPCCode: "UNAVAILABLE", UserMessageZH: "数据库暂不可用"},
	AnalysisInputInvalid: {ID: 1600, Phase: "analysis", Retryable: false, GRPCCode: "INVALID_ARGUMENT", UserMessageZH: "分析输入不完整或格式不支持"},
	AnalysisTimeout: {ID: 1601, Phase: "analysis", Retryable: true, GRPCCode: "DEADLINE_EXCEEDED", UserMessageZH: "分析任务超时"},
	AnalysisRetryExhausted: {ID: 1602, Phase: "analysis", Retryable: false, GRPCCode: "INTERNAL", UserMessageZH: "分析重试次数已耗尽"},
	InternalError: {ID: 1900, Phase: "internal", Retryable: false, GRPCCode: "INTERNAL", UserMessageZH: "系统内部错误"},
}
