"""Generate task collection/analysis status bindings from one contract."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "contracts" / "task-statuses.json"


def _load() -> dict:
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    for dimension in ("collection", "analysis"):
        items = payload.get(dimension) or []
        names = [item["name"] for item in items]
        if not items or len(names) != len(set(names)):
            raise ValueError(f"{dimension} statuses must be non-empty and unique")
        known = set(names)
        for item in items:
            unknown = set(item.get("next") or []) - known
            if unknown:
                raise ValueError(f"unknown {dimension} transitions: {sorted(unknown)}")
            if bool(item["terminal"]) != (len(item.get("next") or []) == 0):
                raise ValueError(f"terminal/next mismatch: {dimension}.{item['name']}")
    return payload


def _python(payload: dict) -> str:
    def enum(name: str, items: list[dict]) -> str:
        rows = "\n".join(f'    {item["name"]} = "{item["name"]}"' for item in items)
        return f"@unique\nclass {name}(str, Enum):\n{rows}\n"
    collection = {item["name"]: item["next"] for item in payload["collection"]}
    analysis = {item["name"]: item["next"] for item in payload["analysis"]}
    return f'''# Code generated by scripts/generate_status_contracts.py; DO NOT EDIT.
from enum import Enum, unique

{enum("CollectionStatus", payload["collection"])}
{enum("AnalysisStatus", payload["analysis"])}
COLLECTION_TRANSITIONS = {json.dumps(collection, ensure_ascii=False, indent=2)}
ANALYSIS_TRANSITIONS = {json.dumps(analysis, ensure_ascii=False, indent=2)}
'''


def _go(payload: dict) -> str:
    rows = []
    for prefix, dimension in (("Collection", "collection"), ("Analysis", "analysis")):
        for item in payload[dimension]:
            rows.append(f'\t{prefix}{item["name"].title().replace("_", "")} = "{item["name"]}"')
    return "// Code generated by scripts/generate_status_contracts.py; DO NOT EDIT.\npackage taskstatus\n\nconst (\n" + "\n".join(rows) + "\n)\n"


def _cpp(payload: dict) -> str:
    rows = []
    for prefix, dimension in (("kCollection", "collection"), ("kAnalysis", "analysis")):
        for item in payload[dimension]:
            rows.append(f'inline constexpr std::string_view {prefix}{item["name"].title().replace("_", "")} = "{item["name"]}";')
    return "// Code generated by scripts/generate_status_contracts.py; DO NOT EDIT.\n#pragma once\n#include <string_view>\nnamespace mini_drop_contract {\n" + "\n".join(rows) + "\n}  // namespace mini_drop_contract\n"


def _javascript(payload: dict) -> str:
    return "// Code generated by scripts/generate_status_contracts.py; DO NOT EDIT.\nexport const TASK_STATUSES = Object.freeze(" + json.dumps(payload, ensure_ascii=False, indent=2) + ");\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = _load()
    outputs = {
        ROOT / "server/app/generated/status_contract.py": _python(payload),
        ROOT / "apiserver/internal/taskstatus/statuses.go": _go(payload),
        ROOT / "native/generated/status_contract.h": _cpp(payload),
        ROOT / "web/src/generated/taskStatuses.js": _javascript(payload),
    }
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("stale generated status contracts: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
