import { act, fireEvent, render, screen } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import AgentDetail from "./AgentDetail";
import { listAgents, listTasks } from "../api/client";
const state = vi.hoisted(() => ({ id: "a", option: vi.fn(), poll: null }));
vi.mock("react-router-dom", () => ({ useParams: () => ({ agentId: state.id }), useNavigate: () => vi.fn() }));
vi.mock("../api/client", () => ({ listAgents: vi.fn(), listTasks: vi.fn() }));
vi.mock("../lib/echarts", () => ({ default: { init: () => ({setOption: state.option, dispose: vi.fn(), resize: vi.fn()}) } }));
vi.mock("../hooks/usePolling", () => ({ default: (callback) => { state.poll = callback; return {}; } }));
const agent = (id, ts, cpu) => ({ id, hostname: id, status: "ONLINE", latest_metrics: { sampled_at_unix_ms: ts, self: { cpu_percent: cpu, rss_mb: 16 } } });
beforeEach(() => { vi.clearAllMocks(); state.id = "a"; listTasks.mockResolvedValue([]); });
it("ignores late responses from another agent and resets the trend on navigation", async () => {
  listAgents.mockResolvedValue([agent("a", 1000, 180)]);
  const view = render(<AgentDetail />);
  await screen.findByText("过去 1 个采样点");
  await act(async () => { await state.poll(); });
  expect(screen.getByText("过去 1 个采样点")).toBeInTheDocument();
  listAgents.mockResolvedValueOnce([agent("a", 2000, 190)]);
  await act(async () => { await state.poll(); });
  expect(screen.getByText("过去 2 个采样点")).toBeInTheDocument();
  expect(state.option.mock.calls.at(-1)[0].yAxis[0].max).toBeUndefined();
  expect(state.option.mock.calls.at(-1)[0].xAxis.type).toBe("time");
  expect(state.option.mock.calls.at(-1)[0].series[0].data).toEqual([[1000, 180], [2000, 190]]);
  let resolveOld;
  listAgents.mockImplementationOnce(() => new Promise((resolve) => { resolveOld = resolve; }));
  fireEvent.click(screen.getByRole("button", { name: /刷新/ }));
  state.id = "b";
  listAgents.mockResolvedValue([agent("b", 3000, 2)]);
  view.rerender(<AgentDetail />);
  await screen.findByText("过去 1 个采样点");
  await act(async () => { resolveOld([agent("a", 4000, 200)]); });
  expect(screen.queryByText("CPU 200.0%")).not.toBeInTheDocument();
  expect(screen.getByText("CPU 2.0%")).toBeInTheDocument();
  expect(screen.getByText("过去 1 个采样点")).toBeInTheDocument();
});
it("shows a request error and retry instead of only claiming the agent does not exist", async () => {
  listAgents.mockRejectedValueOnce(new Error("network unavailable"));
  render(<AgentDetail />);
  await screen.findByText("network unavailable");
  listAgents.mockResolvedValueOnce([agent("a", 1000, 0)]);
  fireEvent.click(screen.getByRole("button", { name: /重\s*试/ }));
  await screen.findByText("CPU 0.0%");
});
