"""Mentor-facing completed diagnosis replays.

The data in this module is an explicitly labelled controlled-fault replay. It is
not mixed into production diagnosis records and must never be presented as a
live incident.
"""

from __future__ import annotations


def get_mentor_complex_showcase() -> dict:
    """Return a difficult, completed diagnosis used to explain Skill evolution."""

    return {
        "case_id": "showcase-noisy-neighbor-io-001",
        "title": "订单服务 CPU 升高，但根因在同宿主机日志压缩进程",
        "replay_mode": True,
        "replay_label": "已完成受控故障回放",
        "source": "白名单故障 Campaign：基线、故障、恢复三阶段快照",
        "status": "COMPLETED",
        "symptom": "订单服务 CPU、P99 延迟和磁盘等待同时升高，单看进程指标很像业务代码热点。",
        "root_cause": "同宿主机日志压缩进程集中执行同步写入，推高磁盘队列；订单服务阻塞在 fsync/writeback 路径，CPU 升高是上下文切换和等待放大的伴随现象。",
        "fix": "限制日志压缩并发并错峰执行，降低其 I/O 优先级；业务进程无需改代码。",
        "first_run": {
            "label": "首次诊断：没有可复用 Skill",
            "duration_seconds": 168,
            "tool_calls": 6,
            "confidence": 0.94,
            "explored_branches": 5,
            "pruned_branches": 3,
            "rounds": [
                {
                    "round": 1,
                    "direction": "建立基线",
                    "tool": "系统指标与业务延迟",
                    "duration_seconds": 24,
                    "decision": "CPU、P99 与磁盘等待同窗升高，不能只按 CPU 热点处理",
                    "outcome": "继续并行验证用户态、锁竞争和 I/O 三个方向",
                },
                {
                    "round": 2,
                    "direction": "用户态热点",
                    "tool": "进程 CPU 采样",
                    "duration_seconds": 31,
                    "decision": "用户态样本仅 18%，热点函数不集中",
                    "outcome": "反证成立，剪掉业务代码热点分支",
                },
                {
                    "round": 3,
                    "direction": "锁竞争",
                    "tool": "线程与锁等待检查",
                    "duration_seconds": 27,
                    "decision": "futex 等待占比仅 3.2%，没有长尾锁持有",
                    "outcome": "反证成立，剪掉锁竞争分支并转向 I/O",
                },
                {
                    "round": 4,
                    "direction": "I/O 到宿主机",
                    "tool": "目标 I/O 与同宿主机进程相关性",
                    "duration_seconds": 42,
                    "decision": "目标写入低但整盘队列为 14，log-compactor 写入 228MB/s",
                    "outcome": "跨进程命中噪声邻居，相关系数为 0.93",
                },
                {
                    "round": 5,
                    "direction": "恢复验证",
                    "tool": "同负载恢复窗口复测",
                    "duration_seconds": 44,
                    "decision": "停止故障后磁盘队列、P99 和 CPU 同时回落",
                    "outcome": "因果闭环成立，允许生成候选 Skill",
                },
            ],
            "nodes": [
                {
                    "id": "symptom",
                    "parent_id": None,
                    "domain": "入口",
                    "title": "订单服务 CPU 与 P99 同时升高",
                    "state": "visited",
                    "evidence": "CPU 72% -> 91%，P99 180ms -> 1.8s",
                },
                {
                    "id": "user-hotspot",
                    "parent_id": "symptom",
                    "domain": "用户态",
                    "title": "怀疑业务热点函数",
                    "state": "refuted",
                    "tool": "进程 CPU 采样",
                    "evidence": "用户态样本仅 18%，热点函数不集中；该分支被剪掉",
                },
                {
                    "id": "lock",
                    "parent_id": "symptom",
                    "domain": "并发",
                    "title": "怀疑锁竞争或线程自旋",
                    "state": "refuted",
                    "tool": "线程与锁等待检查",
                    "evidence": "futex 等待占比 3.2%，无长尾锁持有；该分支被剪掉",
                },
                {
                    "id": "target-io",
                    "parent_id": "symptom",
                    "domain": "I/O",
                    "title": "转向目标进程 I/O",
                    "state": "refuted",
                    "tool": "进程 I/O 与磁盘延迟检查",
                    "evidence": "目标写入量很低，但磁盘利用率 99%、队列深度 14；问题不在目标自身",
                },
                {
                    "id": "peer-scan",
                    "parent_id": "target-io",
                    "domain": "宿主机",
                    "title": "跨进程扫描同宿主机噪声邻居",
                    "state": "confirmed",
                    "tool": "同宿主机进程相关性检查",
                    "evidence": "log-compactor 写入 228MB/s，与订单 P99 的相关系数 0.93",
                },
                {
                    "id": "recovery",
                    "parent_id": "peer-scan",
                    "domain": "恢复验证",
                    "title": "停止故障并同负载复测",
                    "state": "confirmed",
                    "tool": "恢复窗口系统指标",
                    "evidence": "磁盘队列 14 -> 1.2，P99 1.8s -> 205ms，CPU 回落至 74%",
                },
                {
                    "id": "network",
                    "parent_id": "symptom",
                    "domain": "网络",
                    "title": "下游网络异常",
                    "state": "unvisited",
                    "evidence": "已有 I/O 根因闭环，满足停止条件，未继续调用网络工具",
                },
            ],
            "switches": [
                {"from": "用户态", "to": "并发", "reason": "perf 样本未形成业务热点"},
                {"from": "并发", "to": "I/O", "reason": "锁等待占比不足以解释 P99"},
                {"from": "目标进程 I/O", "to": "宿主机", "reason": "目标写入低但整盘拥塞"},
            ],
            "evidence_refs": [
                "snapshot:baseline/order-host",
                "snapshot:fault/order-host",
                "task:process-cpu-profile",
                "task:host-io-correlation",
                "snapshot:recovery/order-host",
            ],
        },
        "generated_skill": {
            "candidate_id": "skill_candidate_io_neighbor_v1",
            "source_report_id": "report_showcase_noisy_neighbor_001",
            "name": "同宿主机 I/O 噪声邻居循证诊断",
            "version": "v1",
            "status": "已通过三类门禁，等待人工发布",
            "action": "新建候选 Skill",
            "source_case": "showcase-noisy-neighbor-io-001",
            "source_trace": "首次诊断的 5 轮实际探索轨迹，不使用初始预设树代替",
            "probe_order": ["系统与 P99 基线", "目标进程 CPU 采样", "锁等待", "目标 I/O", "同宿主机相关性", "恢复复测"],
            "negative_paths": ["无用户态热点时停止深挖业务函数", "锁等待低时停止锁竞争分支", "目标写入低而整盘忙时转向宿主机"],
            "switch_conditions": ["用户态样本 < 30%", "futex 等待 < 10%", "目标写入低且磁盘利用率 > 90%"],
            "evidence_requirements": ["基线、故障、恢复三段快照", "同宿主机写入与业务 P99 相关系数 > 0.8", "故障停止后两项指标同时回落"],
            "stop_conditions": ["根因证据、反证和恢复验证同时满足", "未满足证据门槛时必须拒绝建立根因"],
            "gate_results": [
                {"name": "相似正例", "result": "PASS", "passed": 5, "total": 5},
                {"name": "相似症状反例", "result": "PASS", "passed": 4, "total": 4},
                {"name": "环境迁移", "result": "PASS", "passed": 2, "total": 2},
            ],
        },
        "second_run": {
            "label": "第二次：相似但不完全相同的故障",
            "incident": "另一台主机的备份压缩进程造成同类磁盘拥塞",
            "skill_hit": True,
            "duration_seconds": 62,
            "tool_calls": 3,
            "confidence": 0.92,
            "root_cause_correct": True,
            "path": ["系统与 P99 基线", "目标 I/O 与整盘对比", "同宿主机相关性与恢复复测"],
        },
        "counterexample": {
            "label": "第三次：症状相似但根因不同",
            "incident": "下游网络丢包导致 P99 和 CPU 同时升高",
            "skill_considered": True,
            "skill_applied": False,
            "duration_seconds": 74,
            "tool_calls": 4,
            "root_cause": "下游重传与连接超时",
            "rejection_reason": "磁盘队列与同宿主机写入均正常，不满足 Skill 的必要证据门槛",
            "false_transfer": False,
        },
        "comparison": {
            "before": {"tool_calls": 6, "duration_seconds": 168, "invalid_branches": 3, "confidence": 0.94},
            "after": {"tool_calls": 3, "duration_seconds": 62, "invalid_branches": 0, "confidence": 0.92},
            "improvement": {"tool_calls_percent": 50, "duration_percent": 63, "false_transfer_rate": 0},
        },
    }
